### ISSUE TITLE
Repo permissions

### ISSUE THREAD

**Issue by JohnStrunk** [red-hat-storage/ocs-monkey#3]
@petr-balogh @vasukulkarni 
Could we set up a team in red-hat-storage for ocs-monkey to handle write (merge) permission?
I don't currently have access to review/merge #2

**Comment by petr-balogh** [comment]
Hey @JohnStrunk , I created https://github.com/orgs/red-hat-storage/teams/ocs-monkey-maintainers team and added you and @vasukulkarni  there.  Then went to ocs-monkey project and invited this team with admin permission.   Is this OK? Or you would like to have this team just with write permission? Or other team just with write permission and maintainers should have this admin permission?

**Comment by JohnStrunk** [comment]
Thanks for setting it up. I think this config is good for now.
