### ISSUE TITLE
Fix container build process

### ISSUE THREAD

**Issue by JohnStrunk** [red-hat-storage/ocs-monkey#4]
GH Actions are used to build the ocs-monkey containers. The configuration still points to the location used from when the repo was in my personal account.

We need to:
- [ ] Create new container repos for:
  - The workload container: https://github.com/red-hat-storage/ocs-monkey/blob/e62166087890130b6be2cfd40dcd3610448f8e92/.github/workflows/osio-workload.yml#L12
  - The ocs-monkey generator container: https://github.com/red-hat-storage/ocs-monkey/blob/e62166087890130b6be2cfd40dcd3610448f8e92/.github/workflows/workload-generator.yml#L13
- [ ] Update the above lines to point to the new repos
- [ ] Update the badges in https://github.com/red-hat-storage/ocs-monkey/blob/master/README.md
- [ ] Add GH secrets w/ a bot account that has write access to the above repos
  - `REGISTRY_USERNAME` w/ the bot account name
  - `REGISTRY_PASSWORD` w/ the password
  - Usage: https://github.com/red-hat-storage/ocs-monkey/blob/e62166087890130b6be2cfd40dcd3610448f8e92/.github/workflows/osio-workload.yml#L65
- [ ] Update `workload_runner.py` and `helm/ocs-monkey-generator/values.yaml` to use the new locations

**Comment by jilju** [comment]
@vasukulkarni 
Is there any account already available which we can use to achieve this ?

- [ ] Add GH secrets w/ a bot account that has write access to https://quay.io/repository/ocsci/osio-workload and https://quay.io/repository/ocsci/ocs-monkey-generator
  - `REGISTRY_USERNAME` w/ the bot account name
  - `REGISTRY_PASSWORD` w/ the password
  - Usage: https://github.com/red-hat-storage/ocs-monkey/blob/e62166087890130b6be2cfd40dcd3610448f8e92/.github/workflows/osio-workload.yml#L65
