### ISSUE TITLE
General cleanup

### ISSUE THREAD

**Issue by JohnStrunk** [red-hat-storage/ocs-monkey#5]
- [ ] Remove `.mergify.yml` - Mergify isn't being used any more
- [ ] Update `Dockerfile` and `osio-workload/Dockerfile` labels w/ new repo location

**Comment by jilju** [comment]
Updation of  Dockerfile and osio-workload/Dockerfile labels w/ new repo location will be done in  PR #8 along fix other updates.

**Comment by jilju** [comment]
Both the PR #8 and #9 are merged.
